version: "3.7"

services:
  django:
    container_name: django
    image: ghcr.io/imcoder0000/django-backend:latest
    command: "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=av_db.settings
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - KAKAO_LOGIN_URL=${KAKAO_LOGIN_URL}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - KAKAO_TOKEN_REQUEST_URI=${KAKAO_TOKEN_REQUEST_URI}
      - KAKAO_USER_INFO_REQUEST_URI=${KAKAO_USER_INFO_REQUEST_URI}
      - KAKAO_WITHDRAW_URL=${KAKAO_WITHDRAW_URL}
      - REDIS_HOST=redis-container
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - TOSS_PAYMENTS_BASE_URL=${TOSS_PAYMENTS_BASE_URL}
      - TOSS_PAYMENTS_SECRET_KEY=${TOSS_PAYMENTS_SECRET_KEY}
      - GITHUB_LOGIN_URL=${GITHUB_LOGIN_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
      - GITHUB_TOKEN_REQUEST_URI=${GITHUB_TOKEN_REQUEST_URI}
      - GITHUB_USER_INFO_REQUEST_URI=${GITHUB_USER_INFO_REQUEST_URI}
      - GITHUB_ADMIN_CODE=${GITHUB_ADMIN_CODE}
      - GITHUB_SCOPE=${GITHUB_SCOPE}
      - NAVER_LOGIN_URL=${NAVER_LOGIN_URL}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_REDIRECT_URI=${NAVER_REDIRECT_URI}
      - NAVER_TOKEN_REQUEST_URI=${NAVER_TOKEN_REQUEST_URI}
      - NAVER_USER_INFO_REQUEST_URI=${NAVER_USER_INFO_REQUEST_URI}
      - NAVER_WITHDRAW_URL=${NAVER_WITHDRAW_URL}
      - GOOGLE_LOGIN_URL=${GOOGLE_LOGIN_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_TOKEN_REQUEST_URI=${GOOGLE_TOKEN_REQUEST_URI}
      - GOOGLE_USER_INFO_REQUEST_URI=${GOOGLE_USER_INFO_REQUEST_URI}
      - GOOGLE_REVOKE_URL=${GOOGLE_REVOKE_URL}
      - FASTAPI_URL=https://sj6bo9orbe.execute-api.ap-northeast-2.amazonaws.com
      - FIBER_URL=${FIBER_URL}
    networks:
      - app



volumes:
  db_data:
  redis_data:

networks:
  app:
    external: true
